// AUTO-GENERATED FILE — do not hand-edit.
//
// Pre-computed weekend daily puzzles. Generated by
// `scripts/regenerate-weekend-overrides.cjs`. Saturday targets a 8-move
// optimal; Sunday a 9-move; both apply the strict path-floor (no shortest
// path through a < 4-letter word in either Dict A or Dict B) and cap the
// Dict A vs Dict B gap at 3.
//
// The runtime picker treats this as an override map and short-circuits to
// the entries below for any matching date. If the player's date isn't
// here (e.g. the generator hasn't been re-run lately), the runtime falls
// back to computing the weekend constraints on-device — slower but
// correct.
//
// Regenerate after any change to weekend constraints or to the
// dictionary:
//
//   node scripts/regenerate-weekend-overrides.cjs

import type { DailyOverride } from "./puzzleOverrides";

export const weekendDailyOverrides: Record<string, DailyOverride> = {
  "2026-10-03": { start: "match", target: "tacked" }, // Sat
  "2026-10-04": { start: "switch", target: "phrase" }, // Sun
  "2026-10-10": { start: "boil", target: "luck" }, // Sat
  "2026-10-11": { start: "sine", target: "clashes" }, // Sun
  "2026-10-17": { start: "book", target: "finger" }, // Sat
  "2026-10-18": { start: "shoot", target: "around" }, // Sun
  "2026-10-24": { start: "charmed", target: "want" }, // Sat
  "2026-10-25": { start: "line", target: "bracket" }, // Sun
  "2026-10-31": { start: "dealing", target: "listing" }, // Sat
  "2026-11-01": { start: "found", target: "starred" }, // Sun
  "2026-11-07": { start: "front", target: "slept" }, // Sat
  "2026-11-08": { start: "quite", target: "while" }, // Sun
  "2026-11-14": { start: "barred", target: "dove" }, // Sat
  "2026-11-15": { start: "rash", target: "listen" }, // Sun
  "2026-11-21": { start: "tended", target: "stick" }, // Sat
  "2026-11-22": { start: "dark", target: "flashes" }, // Sun
  "2026-11-28": { start: "style", target: "push" }, // Sat
  "2026-11-29": { start: "minded", target: "poster" }, // Sun
  "2026-12-05": { start: "handle", target: "grave" }, // Sat
  "2026-12-06": { start: "barred", target: "bring" }, // Sun
  "2026-12-12": { start: "forced", target: "washes" }, // Sat
  "2026-12-13": { start: "raced", target: "across" }, // Sun
  "2026-12-19": { start: "front", target: "board" }, // Sat
  "2026-12-20": { start: "prove", target: "amended" }, // Sun
  "2026-12-26": { start: "push", target: "hacker" }, // Sat
  "2026-12-27": { start: "winning", target: "typing" }, // Sun
  "2027-01-02": { start: "belt", target: "pended" }, // Sat
  "2027-01-03": { start: "held", target: "urged" }, // Sun
  "2027-01-09": { start: "tell", target: "dashed" }, // Sat
  "2027-01-10": { start: "stream", target: "agree" }, // Sun
  "2027-01-16": { start: "spoilt", target: "clock" }, // Sat
  "2027-01-17": { start: "fiber", target: "campus" }, // Sun
  "2027-01-23": { start: "soap", target: "flies" }, // Sat
  "2027-01-24": { start: "trace", target: "monkey" }, // Sun
  "2027-01-30": { start: "worm", target: "deprived" }, // Sat
  "2027-01-31": { start: "mark", target: "laying" }, // Sun
  "2027-02-06": { start: "talked", target: "pence" }, // Sat
  "2027-02-07": { start: "halting", target: "kicking" }, // Sun
  "2027-02-13": { start: "fooling", target: "making" }, // Sat
  "2027-02-14": { start: "hire", target: "landed" }, // Sun
  "2027-02-20": { start: "plan", target: "locked" }, // Sat
  "2027-02-21": { start: "cash", target: "launch" }, // Sun
  "2027-02-27": { start: "trick", target: "phase" }, // Sat
  "2027-02-28": { start: "listen", target: "trace" }, // Sun
  "2027-03-06": { start: "bracket", target: "care" }, // Sat
  "2027-03-07": { start: "play", target: "gutter" }, // Sun
  "2027-03-13": { start: "sorted", target: "miss" }, // Sat
  "2027-03-14": { start: "hiring", target: "gleaning" }, // Sun
  "2027-03-20": { start: "creep", target: "stream" }, // Sat
  "2027-03-21": { start: "recent", target: "prove" }, // Sun
  "2027-03-27": { start: "slow", target: "quota" }, // Sat
  "2027-03-28": { start: "beam", target: "power" }, // Sun
};
