// AUTO-GENERATED FILE — do not hand-edit.
//
// Pre-computed weekend daily puzzles. Generated by
// `scripts/regenerate-weekend-overrides.cjs`. Saturday targets a 8-move
// optimal; Sunday a 9-move; both apply the strict path-floor (no shortest
// path through a < 4-letter word in either Dict A or Dict B) and cap the
// Dict A vs Dict B gap at 3.
//
// The runtime picker treats this as an override map and short-circuits to
// the entries below for any matching date. If the player's date isn't
// here (e.g. the generator hasn't been re-run lately), the runtime falls
// back to computing the weekend constraints on-device — slower but
// correct.
//
// Regenerate after any change to weekend constraints or to the
// dictionary:
//
//   node scripts/regenerate-weekend-overrides.cjs

import type { DailyOverride } from "./puzzleOverrides";

export const weekendDailyOverrides: Record<string, DailyOverride> = {
  "2026-07-11": { start: "bass", target: "beaten" }, // Sat
  "2026-07-12": { start: "bash", target: "trailed" }, // Sun
  "2026-07-18": { start: "straw", target: "cured" }, // Sat
  "2026-07-19": { start: "same", target: "ruined" }, // Sun
  "2026-07-25": { start: "burned", target: "save" }, // Sat
  "2026-07-26": { start: "lain", target: "barrel" }, // Sun
  "2026-08-01": { start: "stolen", target: "abide" }, // Sat
  "2026-08-02": { start: "luck", target: "nailed" }, // Sun
  "2026-08-08": { start: "maize", target: "gutter" }, // Sat
  "2026-08-09": { start: "cold", target: "sneaky" }, // Sun
  "2026-08-15": { start: "bull", target: "market" }, // Sat
  "2026-08-16": { start: "joked", target: "inner" }, // Sun
  "2026-08-22": { start: "half", target: "driver" }, // Sat
  "2026-08-23": { start: "ball", target: "flying" }, // Sun
  "2026-08-29": { start: "award", target: "across" }, // Sat
  "2026-08-30": { start: "nick", target: "awaited" }, // Sun
  "2026-09-05": { start: "mislead", target: "wishes" }, // Sat
  "2026-09-06": { start: "curve", target: "tackle" }, // Sun
  "2026-09-12": { start: "life", target: "sender" }, // Sat
  "2026-09-13": { start: "spool", target: "parsed" }, // Sun
  "2026-09-19": { start: "spies", target: "closet" }, // Sat
  "2026-09-20": { start: "table", target: "slowed" }, // Sun
  "2026-09-26": { start: "talk", target: "slower" }, // Sat
  "2026-09-27": { start: "crowd", target: "merge" }, // Sun
  "2026-10-03": { start: "match", target: "tacked" }, // Sat
  "2026-10-04": { start: "switch", target: "phrase" }, // Sun
  "2026-10-10": { start: "boil", target: "luck" }, // Sat
  "2026-10-11": { start: "sine", target: "clashes" }, // Sun
  "2026-10-17": { start: "book", target: "finger" }, // Sat
  "2026-10-18": { start: "shoot", target: "around" }, // Sun
  "2026-10-24": { start: "charmed", target: "want" }, // Sat
  "2026-10-25": { start: "line", target: "bracket" }, // Sun
  "2026-10-31": { start: "dealing", target: "listing" }, // Sat
  "2026-11-01": { start: "found", target: "starred" }, // Sun
  "2026-11-07": { start: "front", target: "slept" }, // Sat
  "2026-11-08": { start: "quite", target: "while" }, // Sun
  "2026-11-14": { start: "barred", target: "dove" }, // Sat
  "2026-11-15": { start: "tray", target: "deprived" }, // Sun
  "2026-11-21": { start: "tended", target: "stick" }, // Sat
  "2026-11-22": { start: "dark", target: "flashes" }, // Sun
  "2026-11-28": { start: "style", target: "push" }, // Sat
  "2026-11-29": { start: "minded", target: "poster" }, // Sun
  "2026-12-05": { start: "handle", target: "grave" }, // Sat
  "2026-12-06": { start: "barred", target: "bring" }, // Sun
  "2026-12-12": { start: "forced", target: "washes" }, // Sat
  "2026-12-13": { start: "raced", target: "across" }, // Sun
  "2026-12-19": { start: "front", target: "board" }, // Sat
  "2026-12-20": { start: "prove", target: "amended" }, // Sun
  "2026-12-26": { start: "push", target: "hacker" }, // Sat
  "2026-12-27": { start: "winning", target: "typing" }, // Sun
  "2027-01-02": { start: "belt", target: "pended" }, // Sat
  "2027-01-03": { start: "held", target: "urged" }, // Sun
};
