/*
 * Generates src/dictionaryData/targets.ts — a curated subset of the full
 * dictionary suitable for use as daily-challenge target words.
 *
 * Heuristic for v1:
 *   - length 4 to 6 letters (Wordle-ish range)
 *   - exclude trivial plurals: `X` where `X` ends in 's' and `X.slice(0,-1)`
 *     is also a word in the dictionary (so 'cats' is out, but 'boss' stays).
 *
 * Re-run any time the input dictionary changes:
 *   node scripts/generate-targets.cjs
 */

const fs = require("fs");
const path = require("path");

const dictDir = path.join(__dirname, "..", "src", "dictionaryData");
const outFile = path.join(dictDir, "targets.ts");
const letters = "abcdefghijklmnopqrstuvwxyz".split("");

const wordGraph = {};
for (const letter of letters) {
  const source = fs.readFileSync(
    path.join(dictDir, `graphLetter_${letter}.js`),
    "utf8"
  );
  const start = source.indexOf("{");
  const end = source.lastIndexOf("}");
  const literal = source.slice(start, end + 1);
  // eslint-disable-next-line no-new-func
  Object.assign(wordGraph, new Function(`return (${literal});`)());
}

const allWords = Object.keys(wordGraph);
const dictSet = new Set(allWords);

const isTrivialPlural = (word) =>
  word.endsWith("s") && dictSet.has(word.slice(0, -1));

const targets = allWords
  .filter((word) => word.length >= 4 && word.length <= 6)
  .filter((word) => !isTrivialPlural(word))
  .sort();

const content =
  "// Generated by scripts/generate-targets.cjs — do not edit by hand.\n" +
  "// Re-run that script to refresh.\n" +
  "export const targetWords: readonly string[] = [\n" +
  targets.map((word) => `  ${JSON.stringify(word)},`).join("\n") +
  "\n];\n";

fs.writeFileSync(outFile, content);
console.log(
  `wrote ${targets.length} target words to ${path.relative(process.cwd(), outFile)}`
);
